# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='ctr_lat',
            field=models.FloatField(default=60.192059),
        ),
        migrations.AddField(
            model_name='district',
            name='ctr_lon',
            field=models.FloatField(default=24.945831),
        ),
    ]
