# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170713_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.District'),
        ),
    ]
