# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170726_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='zip',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
