# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170712_0810'),
        ('services', '0003_auto_20170717_1350'),
    ]

    operations = [
    ]
